services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Path to your backend Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=polygon.settings

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
