# Use an official Node runtime as a parent image
FROM node:18.17.0-alpine

# Set the working directory in the container
WORKDIR /InvestWise/frontend

# Install dependencies
COPY /frontend/package*.json /InvestWise/frontend
RUN npm install

# Copy the rest of the application code
COPY frontend /InvestWise/frontend

# Build the Next.js application
RUN npm run build

# Expose the Next.js port
ENV PORT=3000
EXPOSE 3000

# Run the Next.js application
CMD ["npm", "start"]
