# Generated by Django 4.1.7 on 2023-03-25 02:14
# backend/migrations/0002_build_StockDatabase.py

from backend.models import Stock
from django.db import migrations, transaction
from backend.scripts.stock_utils import update_AllPreviousClose, create_NewStock

watchlist = ['AAPL','ADP','AIG','AMZN', 'AVGO','BAC','BBY','CL','COST','ESS','GE','GS',
                'HD','HPQ','IBM','INTC','JEPI','JNJ','JPM','KO','LOW','MCD','MMM','MSFT',
                'NEE','NVDA','O','PEP','PG','QCOM','QYLD','SCHD','SPGI','SPY','SYY','TGT',
                'TSLA', 'UWMC','VFC','VOO','VTI','VZ','WFC','WMT','XOM']

@transaction.atomic
def build_StockDatabase(apps, schema_editor):
    if Stock.objects.all():
        print("\nStocks found. Updating Previous Close Date...")
        update_AllPreviousClose()
    else:
        print("\nDatabase is empty. Fetching data for all tickers in watchlist...")
        for ticker in watchlist:
            create_NewStock(ticker)

    print("Data is up to date!")
    return

class Migration(migrations.Migration):
    """
        Update database details at migrate, call fetch_ALL_polystockdata
    """

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(build_StockDatabase),
    ]
