# Generated by Django 4.1.7 on 2023-03-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.TextField(default=['AAPL', 'UMWC', 'JEPI', 'PG', 'O']),
        ),
    ]
