# Generated by Django 4.1.7 on 2023-04-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_fetch_polystockdata'),
        ('account', '0002_user_watchlist'),
    ]

    operations = [
    ]
